<?php
declare(strict_types=1);
use DocumentBuilder\Tests\Support\Assert;use DocumentBuilder\Tests\Support\FixtureLoader;use Espo\Modules\DocumentBuilder\Tools\DocumentBuilder\Config\Settings;use Espo\Modules\DocumentBuilder\Tools\DocumentBuilder\Layout\CapabilityRegistry;use Espo\Modules\DocumentBuilder\Tools\DocumentBuilder\Layout\LayoutValidator;use Espo\Modules\DocumentBuilder\Tools\DocumentBuilder\Layout\Node\NodeRegistry;use Espo\Modules\DocumentBuilder\Tools\DocumentBuilder\Layout\StyleResolver;
require dirname(__DIR__).'/bootstrap.php';$root=dirname(__DIR__,2);$module="$root/files/custom/Espo/Modules/DocumentBuilder";$lr="$module/Tools/DocumentBuilder/Layout";require "$module/Tools/DocumentBuilder/Config/Settings.php";foreach(['SchemaVersion.php','StableId.php','Unit.php','Measurement.php','Capability.php','CapabilityStatus.php','CapabilityUnavailable.php','CapabilityNotPublishable.php','CapabilityRegistry.php','Node/NodeKind.php','Node/NodeDefinition.php','Node/UnknownNodeType.php','Node/NodeRegistry.php','ValidationError.php','ValidationResult.php','LayoutValidator.php','StyleResolver.php']as$f)require"$lr/$f";
$settings=new Settings(['enabledSourceEntityTypeList'=>[],'disabledSourceEntityTypeList'=>[],'maxRelationshipDepth'=>2,'maxElements'=>500,'maxNestingDepth'=>8,'maxSections'=>100,'allowedFontList'=>['DejaVu Sans'],'customPageSizeList'=>[]]);$validator=new LayoutValidator($settings,NodeRegistry::phase19(),CapabilityRegistry::phase19());$layout=(new FixtureLoader("$root/tests/fixtures"))->json('layout/phase-08-default.json');$box=fn()=>array_fill_keys(['top','right','bottom','left'],['value'=>0,'unit'=>'mm']);
$layout['document']['style']=['fontFamily'=>'DejaVu Sans','fontSize'=>['value'=>11,'unit'=>'pt'],'color'=>'#222222','lineHeight'=>1.3];$layout['capabilities']=['layout.flow'];$layout['sections']=[['id'=>'section','type'=>'flow-section','children'=>[['id'=>'text','type'=>'static-text','text'=>'Țară și știință','style'=>['color'=>'#0055AA','backgroundColor'=>'#FFFFFF','opacity'=>0.8,'fontWeight'=>'700','fontStyle'=>'italic','textDecoration'=>'underline','letterSpacing'=>['value'=>0.5,'unit'=>'pt'],'textTransform'=>'uppercase','width'=>['value'=>80,'unit'=>'percent'],'border'=>['width'=>['value'=>1,'unit'=>'pt'],'style'=>'solid','color'=>'#000000']]]],'margin'=>$box(),'padding'=>$box(),'minHeight'=>['value'=>20,'unit'=>'mm'],'keepTogether'=>false,'startNewPage'=>false,'style'=>['horizontalAlignment'=>'center']]];
$result=$validator->validate($layout);Assert::isTrue($result->isValid(),'Canonical style rejected: '.implode(',',array_map(fn($e)=>$e->code(),$result->errors())));$codes=fn($v)=>array_map(fn($e)=>$e->code(),$validator->validate($v)->errors());
foreach([['css','position:fixed','property.unknown'],['fontFamily','Bad url(javascript:1)','style.fontFamily'],['color','expression(alert(1))','value.color'],['opacity',2,'style.opacity'],['textTransform','url','style.enum'],['letterSpacing',['value'=>101,'unit'=>'pt'],'style.letterSpacing'],['width',['value'=>101,'unit'=>'percent'],'style.dimension']]as[$key,$value,$code]){$bad=$layout;$bad['sections'][0]['children'][0]['style'][$key]=$value;Assert::isTrue(in_array($code,$codes($bad),true),"Unsafe/invalid style $key accepted.");}
$resolver=new StyleResolver(['DejaVu Sans']);$resolved=$resolver->resolve($layout['document']['defaults'],$layout['document']['style'],$layout['sections'][0]['style'],$layout['sections'][0]['children'][0]['style']);Assert::same('#0055AA',$resolved['color'],'Element style did not override document style.');Assert::same('center',$resolved['horizontalAlignment'],'Section inheritance failed.');$fallback=$resolver->resolve($layout['document']['defaults'],['fontFamily'=>'Unknown Font']);Assert::same('DejaVu Sans',$fallback['fontFamily'],'Controlled font fallback failed.');
echo"Phase 22 server style validation, inheritance, font fallback, and unsafe-CSS tests passed.\n";
