'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../..'),source=path.join(root,'files/client/custom/modules/document-builder/src');const cache=new Map();let active;
function define(dependencies,factory){active={dependencies,factory};}function load(name){if(cache.has(name))return cache.get(name);active=null;new Function('define',fs.readFileSync(path.join(source,`${name.replace(/^document-builder:/,'')}.js`),'utf8'))(define);const value=active.factory(...active.dependencies.map(load));cache.set(name,value);return value;}
const StyleResolver=load('document-builder:editor/style/style-resolver');const FlowStructure=load('document-builder:editor/flow/flow-structure');const EditorState=load('document-builder:editor/state/editor-state');const UpdateNodeCommand=load('document-builder:editor/commands/update-node');const LayoutPrecheck=load('document-builder:editor/validation/layout-precheck');
const layout=JSON.parse(fs.readFileSync(path.join(root,'tests/fixtures/layout/phase-08-default.json')));const box=()=>Object.fromEntries(['top','right','bottom','left'].map(k=>[k,{value:0,unit:'mm'}]));
layout.capabilities=['layout.flow'];layout.document.style={color:'#111111',fontWeight:'normal'};layout.sections=[{id:'section',type:'flow-section',children:[{id:'paragraph',type:'paragraph',content:[{type:'text',text:'Știință și țară',marks:[]}],alignment:'start',style:{fontWeight:'bold',textTransform:'uppercase'}}],margin:box(),padding:box(),minHeight:{value:20,unit:'mm'},keepTogether:false,startNewPage:false,style:{color:'#AA0000',fontFamily:'DejaVu Sans'}}];
const resolver=new StyleResolver(['DejaVu Sans']);const resolved=resolver.resolve(layout,'paragraph');assert.equal(resolved.color,'#AA0000');assert.equal(resolved.fontWeight,'bold');assert.equal(resolved.textTransform,'uppercase');assert.equal(layout.sections[0].children[0].content[0].text,'Știință și țară');
const css=resolver.toCss({...resolved,backgroundColor:'#FFFFFF',letterSpacing:{value:1.5,unit:'pt'},width:{value:50,unit:'percent'}},value=>value*2);assert.match(css,/font-family: 'DejaVu Sans'/);assert.match(css,/letter-spacing: 1.5pt/);assert.match(css,/width: 50%/);assert.doesNotMatch(css,/javascript|url\(/i);
layout.sections[0].children[0].style.fontFamily='Untrusted url(javascript:1)';assert.equal(resolver.resolve(layout,'paragraph').fontFamily,'DejaVu Sans');delete layout.sections[0].children[0].style.fontFamily;
const state=new EditorState(layout);assert.equal(state.execute(new UpdateNodeCommand('paragraph',{style:{color:'#0066AA',fontStyle:'italic'}})),true);assert.equal(state.undo(),true);assert.equal(state.redo(),true);const reloaded=JSON.parse(JSON.stringify(state.getLayout()));assert.equal(reloaded.sections[0].children[0].style.fontStyle,'italic');assert.equal(new LayoutPrecheck([],{}).check(reloaded).valid,true);
reloaded.sections[0].children[0].style={css:'position:fixed;background:url(javascript:1)'};assert.equal(new FlowStructure().validateLayout(reloaded).length>0,true);
console.log('Phase 22 inheritance, CSS mapping, font fallback, Romanian text, history, reload, and precheck tests passed.');
